export const DATA_REQUEST = "DATA_REQUEST";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_ERROR = "DATA_ERROR";

export const CONSTRUCTOR_INGREDIENT_REQUEST = "CONSTRUCTOR_INGREDIENT_REQUEST";
export const CONSTRUCTOR_INGREDIENT_SUCCESS = "CONSTRUCTOR_INGREDIENT_SUCCESS";
export const CONSTRUCTOR_INGREDIENT_ERROR = "CONSTRUCTOR_INGREDIENT_ERROR";
export const CONSTRUCTOR_INGREDIENT_INITIAL = "CONSTRUCTOR_INGREDIENT_INITIAL";
export const CONSTRUCTOR_INGREDIENT_PRICE_SET = "CONSTRUCTOR_INGREDIENT_PRICE_SET";
export const CONSTRUCTOR_INGREDIENT_ADD_BUN = "CONSTRUCTOR_INGREDIENT_ADD";
export const CONSTRUCTOR_INGREDIENT_ADD_INGREDIENTS = "CONSTRUCTOR_INGREDIENT_ADD_INGREDIENTS";
export const CONSTRUCTOR_INGREDIENT_DELETE_INGREDIENTS = "CONSTRUCTOR_INGREDIENT_DELETE_INGREDIENTS";
export const CONSTRUCTOR_INGREDIENT_REPLACE = "CONSTRUCTOR_INGREDIENT_REPLACE";

export const MODAL_INGREDIENT_OPEN = "MODAL_INGREDIENT_OPEN";
export const MODAL_INGREDIENT_CLOSE = "MODAL_INGREDIENT_CLOSE";
export const MODAL_ORDER_SET = "MODAL_ORDER_SET";
export const MODAL_ORDER_OPEN = "MODAL_ORDER_OPEN";
export const MODAL_ORDER_CLOSE = "MODAL_ORDER_CLOSE";

export const DND_INGREDIENT_ADD = "DND_INGREDIENT_ADD";
export const DND_REPLACE_IT_SET = "DND_REPLACE_IT_SET";

export const INGREDIENT_TAB_SET = "INGREDIENT_TAB_SET";